- name: Deploy to EC2
  uses: appleboy/ssh-action@v1.0.0
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ${{ secrets.EC2_USER }}
    key: ${{ secrets.EC2_SSH_KEY }}
    port: 22
    script: |
      DEPLOY_DIR="/var/www/app"
      mkdir -p "$DEPLOY_DIR"
      cd "$DEPLOY_DIR"
      if [ -d .git ]; then
        git reset --hard
        git clean -fd
        git pull origin main
      else
        git clone https://github.com/${{ github.repository }} .
      fi
      npm install --production
      pm2 restart app || pm2 start index.js --name app
      pm2 save
