name: Node.js CI/CD to EC2

on:
  push:
    branches: [ main ]  # or 'master' if your repo uses master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js locally (for testing)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20 # or your preferred version

      # 3️⃣ Install dependencies locally
      - name: Install dependencies
        run: npm install

      # 4️⃣ Run tests
      - name: Run tests
        run: npm test

      # 5️⃣ Copy code to EC2
      - name: Deploy code to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: "./"
          target: "/var/www/github_actions"

      # 6️⃣ SSH into EC2 to install Node.js, PM2, dependencies and restart app
      - name: SSH and restart PM2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Update packages
            sudo apt-get update -y

            # Install Node.js 20 if not installed
            if ! command -v node &> /dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi

            # Install PM2 globally if not installed
            if ! command -v pm2 &> /dev/null; then
              sudo npm install -g pm2
            fi

            # Navigate to project folder
            cd /var/www/github_actions

            # Install production dependencies
            npm install --production

            # Start or reload app with PM2
            if pm2 list | grep -q "my-app"; then
              pm2 reload my-app
            else
              pm2 start ecosystem.config.js --env production --name my-app
            fi

            # Save PM2 process list
            pm2 save
